### PR TITLE
Updated Postgres configs

### PR DESCRIPTION
**Pull request by D-Bits**
With better conformity to the current version of develop.

### CODE REVIEW

**Comment by denisemauldin** [comment]
Can you add the commands for creating a docker volume with the appropriate name to the README.md please?

**Comment by crg253** [comment]
It looks like the readme contains two references to POSTGRES_PASSWORD. Also looks like setttings.py contains POSTGRES_PASS instead of POSTGRESS_PASSWORD

**Comment by crg253** [comment]
Are we planning to create an example env with all variables so that it's not required to create and env file?

**Comment by denisemauldin** [comment]
To copy my comments from slack to here:
1) Please add the commands for creating a docker volume to the README file before the commands that use docker-compose to build the images and create the containers.
2) Please make sure that the `example.env` file can just be copied into the correct file and used without editing.  This file won't be used in production (and neither will the docker-compose.yml) file, so it's safe to have pseudo-production values to make sure that the development environment is usable with little to no knowledge of docker/docker-compose.

**Comment by crg253** [comment]
Dana, I think we wanted those variables in the example env file.

**Pull request closed without merging**
